language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - ruby-head
env:
  - USE_REFINES=true USE_COVERALLS=true
  - USE_REFINES=true USE_COVERALLS=false
  - USE_REFINES=false USE_COVERALLS=true
  - USE_REFINES=false USE_COVERALLS=false
